### PR TITLE
Fix for issue #109

### PR DESCRIPTION
**Pull request by larsga**
We ensure that empty table cells in the input have at least an empty paragraph in the output.

Note that this PR builds on the "refactor tests" PR, so that needs to be merged first.

### CODE REVIEW

**Comment by larsga** [comment]
And I see my commits are now suddenly unverified again. I don't know why, but will fix that.

**Comment by drmacro** [comment]
I'm going to close this PR because the branch is out of date and we can get the useful stuff from this branch manually or via cherry pick if needed.

We can resolve on the most appropriate code fix once the other PRs have been integrated--ultimately it's a small change to the table handling.

**Comment by larsga** [comment]
This branch still has commits that we need to get onto develop, so reopening it.

**Comment by larsga** [comment]
The fix for issue #134 was basically a fix for the same issue as this PR, but that fix was too simple. It's necessary for table cells to *end* with a paragraph if Word is to be happy. This PR has two automated tests that verify this, and the code currently in the repo fails those two tests.

I've now merged in all the code from the repo, and then reapplied these fixes on top.

It would be great if we could get this PR merged, because this is a fix we really need in our software. We have been using our own build of Wordinator (which has this fix), but we would very much like to switch to the standard Wordinator. That requires this issue to be fixed, though.

**Comment by ekimbernow** [comment]
Closing as complete.

I manually copied the code from this PR into the code on the develop branch. New test cases and update empty table cell cases pass, generated Word docs open without error.

**Comment by larsga** [comment]
Thanks for incorporating the fix. I don't really care how it's done, as long as the problems get fixed.

**Pull request closed without merging**
